-- Intentionally empty.
--
-- Religious quotations, translations, biographies, and citations must never be
-- invented for development convenience. Use reviewed records supplied by the
-- archive's editors, or synthetic non-religious fixtures inside automated tests.
